<?php
/**
 * @file
 * @author: William Panting
 * This is the global code for islandora_json_to_list_viewer
 */

/**
 * This function is the hook into the 'islandora viewer sphere'.
 *
 * It reports that this module can handle the JSON mime type and the theme
 * function to call to use it.
 *
 * @param string $mime_type
 *   The mime_type that is being queried for
 *
 * @return mixed
 *   array: 'application/json'=>'islandora_JSON_to_list'
 *   string : 'islandora_JSON_to_list'
 */
function islandora_json_to_list_viewer_islandora_viewers($mime_type = NULL) {
  if ($mime_type == NULL) {
    return array('application/json' => 'islandora_JSON_to_list');
  }
  elseif ($mime_type == 'application/json') {
    return 'islandora_JSON_to_list';
  }
}

/**
 * This function makes available the islandora_JSON_to_list theme.
 *
 * The theme will display an HTML unordered list
 *
 * @return array
 *   the themes available from this module
 */
function islandora_json_to_list_viewer_theme() {
  return array(
    'islandora_JSON_to_list' => array(
      'variables' => array(
        'pid' => NULL,
        'dsid' => 'SWF',
      ),
      'template' => 'islandora_JSON_to_list',
    ),
  );
}

/**
 * Preprocessor function that will prepare to display JSON data as an HTML list.
 *
 * It will take the JSON and format as a nested array in preparation for
 * themeing.
 *
 * @param array $vars
 *   The variables to prepare for themeing
 */
function islandora_json_to_list_viewer_preprocess_islandora_JSON_to_list(&$vars) {
  $fedora_object = islandora_object_load($vars['pid']);
  $vars['JSON_datastream'] = json_decode($fedora_object[$vars['dsid']]->content);
}
